[book]
authors = ["sawurora"]
language = "en"
multilingual = false
src = "src"
title = "Wikiplum"

[preprocessor]

[preprocessor.pagetoc]

[output]

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]
