on:
  push:
    branches:
      - main
      - actions-build
    workflow_dispatch: 

  permissions:
    contents: read
    pages: write
    id-token: write

  # Allow one concurrent deployment
  concurrency:
    group: pages
    cancel-in-progress: true

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        run: cargo install mdbook mdbook-pagetoc && cargo install --path mdbook-infobox

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build page
        run: mdbook build 

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./book

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
